name: GitOps Continuous Delivery

on:
  workflow_dispatch:

  workflow_run:
    workflows:
      - SecureOps Enterprise DevSecOps Pipeline
    types:
      - completed

permissions:
  contents: write

env:
  IMAGE_NAME: anant1102/secureops-backend

jobs:

  gitops:

    if: |
      github.event_name == 'workflow_dispatch' ||
      github.event.workflow_run.conclusion == 'success'

    runs-on: ubuntu-latest

    steps:

    ############################################################
    # Checkout SecureOps Repository
    ############################################################

    - name: Checkout SecureOps Repository
      uses: actions/checkout@v4

    ############################################################
    # Checkout Enterprise GitOps Repository
    ############################################################

    - name: Checkout GitOps Repository
      uses: actions/checkout@v4
      with:
        repository: Anant1102/Enterprise-GitOps-Platform
        token: ${{ secrets.GITOPS_PAT }}
        ref: main
        path: gitops

    ############################################################
    # Verify Repository
    ############################################################

    - name: Verify GitOps Repository
      run: |
        echo "======================================="
        echo "GitOps Repository Cloned Successfully"
        echo "======================================="
        ls -R gitops

    ############################################################
# Update Helm Values
############################################################

    - name: Update Image Tag
      run: |
    
        IMAGE_TAG=${{ github.sha }}
    
        echo "Updating Helm values..."
    
        sed -i "s/tag:.*/tag: ${IMAGE_TAG}/" gitops/charts/secureops/values-dev.yaml
        sed -i "s/tag:.*/tag: ${IMAGE_TAG}/" gitops/charts/secureops/values-qa.yaml
        sed -i "s/tag:.*/tag: ${IMAGE_TAG}/" gitops/charts/secureops/values-prod.yaml
    
        echo "Updated values-dev.yaml"
        cat gitops/charts/secureops/values-dev.yaml
    
        echo "Updated values-qa.yaml"
        cat gitops/charts/secureops/values-qa.yaml
    
        echo "Updated values-prod.yaml"
        cat gitops/charts/secureops/values-prod.yaml

    ############################################################
# Commit Changes
############################################################

    - name: Commit Changes
    
      run: |
    
        cd gitops
    
        git config user.name "github-actions"
    
        git config user.email "github-actions@github.com"
    
        git add .
    
        git diff --cached --quiet || git commit -m "Updated image tag to ${{ github.sha }}"
    
        git push
